### ISSUE TITLE
Make this plugin available in 5.x

### ISSUE THREAD

**Issue by omercnet** [logstash-plugins/logstash-output-gelf#23]
This plugin is currently unavailable in logstash 5.x
Are there any known limitations ?

**Comment by runningman84** [comment]
it looks like you can install it with the logstash plugin command, but I am wondering why this plugin isn't included by default. This means a simple deb/rpm upgrade will break existing installations.

**Comment by runningman84** [comment]
funny enough the gelf input plugin is included by default

@jordansissel please advice

**Comment by omercnet** [comment]
Using the plugin install it fails because it detected it from here and the base logstash gem version is too low

**Comment by omercnet** [comment]
tried again with the latest logstash (5.1.1) and it seems to work just fine
```
# logstash -V
logstash 5.1.1
# logstash-plugin install logstash-output-gelf
Validating logstash-output-gelf
Installing logstash-output-gelf
Installation successful
```

**Comment by longirun** [comment]
I'm not able to install it on v 5.1.1 having the same issue with `logstash-core-event-java`

```
C:\logstash\5.1.1\bin>logstash -V
logstash 5.1.1
jruby 1.7.25 (1.9.3p551) 2016-04-13 867cb81 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17 +jit [Windows 7-amd64]
java 1.8.0_65 (Oracle Corporation)
jvm Java HotSpot(TM) 64-Bit Server VM / 25.65-b01
```

```
C:\logstash\5.1.1\bin>logstash-plugin.bat install logstash-output-gelf
Validating logstash-output-gelf
Installing logstash-output-gelf
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.1.1), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.1.1'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported
```
