### ISSUE TITLE
logstash-output-gelf broken with logstash 6.0.0

### ISSUE THREAD

**Issue by olafkewl** [logstash-plugins/logstash-output-gelf#32]
The output plugin does not work with latest logstash release (6.0.0 at this time)

Plugin installed this way :
`logstash-plugin install logstash-output-gelf`

Using the same config file as previous working version :
`gelf {
host => 'graylog-server-IP'
port => 12201
}`

It fails with this error :
`[2017-11-30T11:11:29,507][FATAL][logstash.runner ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method time' for nil:NilClass>, :backtrace=>["/tmp/logstash/logstash-core/lib/logstash/timestamp.rb:13:in<=>'", "org/jruby/RubyComparable.java:150:in =='", "/tmp/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-gelf-3.1.4/lib/logstash/outputs/gelf.rb:146:inblock in receive'", "org/jruby/RubyHash.java:1343:in each'", "/tmp/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-gelf-3.1.4/lib/logstash/outputs/gelf.rb:145:inreceive'", "/tmp/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in block in multi_receive'", "org/jruby/RubyArray.java:1734:ineach'", "/tmp/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in multi_receive'", "/tmp/logstash/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:22:inmulti_receive'", "/tmp/logstash/logstash-core/lib/logstash/output_delegator.rb:49:in multi_receive'", "/tmp/logstash/logstash-core/lib/logstash/pipeline.rb:538:inblock in output_batch'", "org/jruby/RubyHash.java:1343:in each'", "/tmp/logstash/logstash-core/lib/logstash/pipeline.rb:536:inoutput_batch'", "/tmp/logstash/logstash-core/lib/logstash/pipeline.rb:481:in worker_loop'", "/tmp/logstash/logstash-core/lib/logstash/pipeline.rb:439:inblock in start_workers'"]}`

**Comment by hassanbabaie** [comment]
I'm using Logstash 6.X do we know if this is still an issue with this plugin version 3.1.4

**Comment by olafkewl** [comment]
I've just tested with a fresh logstash-6.1.3 and it works as expected !
We're just missing the "TCP" now ;-)
